### ISSUE TITLE
Linux/Mac doesn't work due to missing executable bit for Posix file systems

### ISSUE THREAD

**Issue by icornett** [MertSenel/Hcl2PS#10]
Posix file systems without an executable bit think that hcl2json is a document and thus can't execute it.

#9  fixes the issue by setting the bit

**Comment by MertSenel** [comment]
I've closed this issue as this is as expected, explained in the Pull Request comment. https://github.com/MertSenel/Hcl2PS/pull/9#issuecomment-1685140138
