### ISSUE TITLE
Unable to run / import

### ISSUE THREAD

**Issue by gjasny** [MertSenel/Hcl2PS#4]
Hello,

I tried to run version `0.2.0` but ran into two problems:

Getting the help text in the PowerShell ISE fails:
```
> Import-Module Hcl2PS
Get-ChildItem : Cannot find path 'C:\Program Files\WindowsPowerShell\Modules\Hcl2PS\0.2.0\Private' because it does not exist. 
```

That's happening because there is no `Private` folder:

```
C:\Program Files\WindowsPowerShell\Modules\Hcl2PS\0.2.0>tree
Folder PATH listing
Volume serial number is B657-1BD1
C:.
├───.github
│   └───workflows
├───bin
│   └───0.5.0
├───media
├───Public
└───__tests__
    └───testData
```

That's probably due to: https://github.com/MertSenel/Hcl2PS/blob/d3634be0d3a508f3dafcce1fab54190f3b1bdf1b/Hcl2PS.psm1#L3-L5

The other problem is that platform detection fails because `$IsWindows` is not set on my Windows 10 PowerShell:
```
 PS C:\Users\gregor.jasny\Documents\SGmapping> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  2364    


PS C:\Users\gregor.jasny\Documents\SGmapping> cmd ver
Microsoft Windows [Version 10.0.19044.2486]
(c) Microsoft Corporation. All rights reserved. 
```

Thanks,
Gregor

**Comment by gjasny** [comment]
Probably I need PowerShell 6. Could you please make the code PowerShell 5 clean or add a version check at package level?

**Comment by MertSenel** [comment]
Hi Gregor, thanks for raising this although I don't have a hard goal of supporting ps5, I'll look into to it to see how much effort it would take to make it backwards compatible. Depending on complexity, I can surely update the module to support ps5.

**Comment by gjasny** [comment]
Thanks for looking into it. The other module I depend on is AzureAD which **only** works on ps5. 

In case you decide against backwards compatibility, maybe you could add a `#Requires -Version` [statement](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_requires?view=powershell-5.1) into your code so that the next unlucky gets a more pointed error message.

Thanks!

**Comment by MertSenel** [comment]
Hi @gjasny, I've published a new version `0.4.0` from my testing this should fix the issue of installation from gallery and Powershell 5 support. I would appreciate if you can also validate and post feedback of how did you go. Thanks.

**Comment by gjasny** [comment]
Thank you! Works like a charm!

**Comment by MertSenel** [comment]
Awesome, thanks for reporting it.
